version: "2"
use_cases:
- name: default
  sections:
  - name: terraform
    groups:
    - name: application
      technologies: [terraform]
      vars:
      - name: Team
        description: The team responsible for this environment
        key: resource_team
        widget: dropdown
        type: string
        values: ["Team A", "Team B", "Team C"]
      - name: Environment
        description: The environment to filter resources by
        key: resource_env
        widget: dropdown
        type: string
        values: ["demo", "staging"]
      - name: Data source
        key: data_source
        widget: dropdown
        type: string
        values: ["users", "teams"]
        default: "users"
      - name: Chosen data
        description: "The chosen item from the subset of mock data"
        key: chosen_data
        widget: auto_complete
        type: string
        values_ref: https://robertparkin.github.io/data/${data_source}.json
        required: true
